/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 17-juin-2020 00:37:39 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Chauffeur_Vehicule]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Chauffeur] DROP CONSTRAINT [FK_Chauffeur_Vehicule]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ClientTrajet_Client]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ClientTrajet] DROP CONSTRAINT [FK_ClientTrajet_Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_ClientTrajet_Trajet]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [ClientTrajet] DROP CONSTRAINT [FK_ClientTrajet_Trajet]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Trajet_Chauffeur]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Trajet] DROP CONSTRAINT [FK_Trajet_Chauffeur]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Admin]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Admin]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Chauffeur]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Chauffeur]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Client]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Client]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[ClientTrajet]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [ClientTrajet]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Trajet]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Trajet]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Vehicule]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Vehicule]
GO

/* Create Tables */

CREATE TABLE [Admin]
(
	[admId] uniqueidentifier NOT NULL,
	[admNom] varchar(50) NOT NULL,
	[admPseudo] varchar(30) NOT NULL,
	[admMotDePasse] varchar(250) NOT NULL,
	[admPhoto] varchar(250) NOT NULL
)
GO

CREATE TABLE [Chauffeur]
(
	[chaId] uniqueidentifier NOT NULL,
	[chaNom] varchar(50) NOT NULL,
	[chaEmail] varchar(50) NOT NULL,
	[chaMotDePasse] varchar(250) NOT NULL,
	[chaTelephone] varchar(13) NOT NULL,
	[chaAdresse] varchar(50) NOT NULL,
	[chaQuartier] varchar(30) NOT NULL,
	[chaDateNaissance] date NOT NULL,
	[chaSexe] varchar(1) NOT NULL,
	[chaPhoto] varchar(250) NULL,
	[chaSolde] float NOT NULL,
	[chaDisponibilite] smallint NOT NULL,
	[vehId] uniqueidentifier NOT NULL
)
GO

CREATE TABLE [Client]
(
	[cliId] uniqueidentifier NOT NULL,
	[cliNom] varchar(50) NOT NULL,
	[cliEmail] varchar(50) NOT NULL,
	[cliMotDePasse] varchar(250) NOT NULL,
	[cliTelephone] varchar(13) NOT NULL,
	[cliAdresse] varchar(50) NOT NULL,
	[cliQuartier] varchar(30) NOT NULL,
	[cliDateNaissance] date NULL,
	[cliSexe] varchar(1) NOT NULL,
	[cliPhoto] varchar(250) NOT NULL,
	[cliSolde] float NOT NULL,
	[cliIdFacebook] varchar(250) NULL,
)
GO

CREATE TABLE [ClientTrajet]
(
	[ctrId] uniqueidentifier NOT NULL,
	[cliId] uniqueidentifier NOT NULL,
	[traId] uniqueidentifier NOT NULL,
	[ctrNombrePersonne] smallint NOT NULL,
	[ctrTypePaiement] varchar(11) NOT NULL
)
GO

CREATE TABLE [Trajet]
(
	[traId] uniqueidentifier NOT NULL,
	[traDepart] varchar(100) NOT NULL,
	[traLatitudeDepart] varchar(30) NOT NULL,
	[traLongitudeDepart] varchar(30) NOT NULL,
	[traDestination] varchar(100) NOT NULL,
	[traLatitudeDestination] varchar(30) NOT NULL,
	[traLongitudeDestination] varchar(30) NOT NULL,
	[traDistance] float NOT NULL,
	[traDuree] varchar(15) NOT NULL,
	[traDateHeureCommande] datetime NOT NULL,
	[traTypeVehicule] varchar(7) NOT NULL,
	[traNombreClient] smallint NOT NULL,
	[traPartageTaxi] smallint NOT NULL,
	[traEtat] varchar(8) NOT NULL,
	[chaId] uniqueidentifier NOT NULL,
	[traPrixTotal] float NOT NULL,
	[traMontantParClient] float NOT NULL
)
GO

CREATE TABLE [Vehicule]
(
	[vehId] uniqueidentifier NOT NULL,
	[vehType] varchar(7) NOT NULL,
	[vehNom] varchar(30) NOT NULL,
	[vehLicence] varchar(4) NOT NULL,
	[vehImmatriculation] varchar(9) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Admin] 
 ADD CONSTRAINT [PK_Admin]
	PRIMARY KEY CLUSTERED ([admId] ASC)
GO

ALTER TABLE [Chauffeur] 
 ADD CONSTRAINT [PK_Chauffeur]
	PRIMARY KEY CLUSTERED ([chaId] ASC)
GO

ALTER TABLE [Chauffeur] 
 ADD CONSTRAINT [CHK_Chauffeur_Sexe] CHECK (chaSexe in ('H','F'))
GO

ALTER TABLE [Chauffeur] 
 ADD CONSTRAINT [CHK_Chauffeur_Solde] CHECK (chaSolde>=0)
GO

ALTER TABLE [Chauffeur] 
 ADD CONSTRAINT [CHK_Chauffeur_Disponibilite] CHECK (chaDisponibilite between 0 and 1)
GO

ALTER TABLE [Client] 
 ADD CONSTRAINT [PK_Client]
	PRIMARY KEY CLUSTERED ([cliId] ASC)
GO

ALTER TABLE [Client] 
 ADD CONSTRAINT [CHK_Client_Sexe] CHECK (cliSexe in ('','H','F'))
GO

ALTER TABLE [Client] 
 ADD CONSTRAINT [CHK_Client_Solde] CHECK (cliSolde>=0)
GO

ALTER TABLE [ClientTrajet] 
 ADD CONSTRAINT [PK_ClientTrajet]
	PRIMARY KEY CLUSTERED ([ctrId] ASC)
GO

ALTER TABLE [ClientTrajet] 
 ADD CONSTRAINT [CHK_ClientTrajet_NombrePersonne] CHECK (ctrNombrePersonne between 1 and 4)
GO

ALTER TABLE [ClientTrajet] 
 ADD CONSTRAINT [CHK_ClientTrajet_TypePaiement] CHECK (ctrTypePaiement in ('par espèce','par QR Code'))
GO

ALTER TABLE [Trajet] 
 ADD CONSTRAINT [PK_Trajet]
	PRIMARY KEY CLUSTERED ([traId] ASC)
GO

ALTER TABLE [Trajet] 
 ADD CONSTRAINT [CHK_Trajet_TypeVehicule] CHECK (traTypeVehicule in ('voiture','moto'))
GO

ALTER TABLE [Trajet] 
 ADD CONSTRAINT [CHK_Trajet_NombreClient] CHECK (traNombreClient between 1 and 4)
GO

ALTER TABLE [Trajet] 
 ADD CONSTRAINT [CHK_Trajet_PartageTaxi] CHECK (traPartageTaxi between 0 and 1)
GO

ALTER TABLE [Trajet] 
 ADD CONSTRAINT [CHK_Trajet_Etat] CHECK (traEtat in ('à venir','en cours','terminé','annulé'))
GO

ALTER TABLE [Vehicule] 
 ADD CONSTRAINT [PK_Vehicule]
	PRIMARY KEY CLUSTERED ([vehId] ASC)
GO

ALTER TABLE [Vehicule] 
 ADD CONSTRAINT [CHK_Vehicule_Type] CHECK (vehType in ('moto','voiture'))
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Chauffeur] ADD CONSTRAINT [FK_Chauffeur_Vehicule]
	FOREIGN KEY ([vehId]) REFERENCES [Vehicule] ([vehId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ClientTrajet] ADD CONSTRAINT [FK_ClientTrajet_Client]
	FOREIGN KEY ([cliId]) REFERENCES [Client] ([cliId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [ClientTrajet] ADD CONSTRAINT [FK_ClientTrajet_Trajet]
	FOREIGN KEY ([traId]) REFERENCES [Trajet] ([traId]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Trajet] ADD CONSTRAINT [FK_Trajet_Chauffeur]
	FOREIGN KEY ([chaId]) REFERENCES [Chauffeur] ([chaId]) ON DELETE No Action ON UPDATE No Action
GO


/* MODIFICATION  */

/* SEQUENTIALID */
ALTER TABLE Admin
    ADD CONSTRAINT DF_admId DEFAULT newsequentialid() FOR admId
go

ALTER TABLE Chauffeur
    ADD CONSTRAINT DF_chaId DEFAULT newsequentialid() FOR chaId
go

ALTER TABLE Client
    ADD CONSTRAINT DF_cliId DEFAULT newsequentialid() FOR cliId
go

ALTER TABLE ClientTrajet
    ADD CONSTRAINT DF_ctrId DEFAULT newsequentialid() FOR ctrId
go

ALTER TABLE Trajet
    ADD CONSTRAINT DF_traId DEFAULT newsequentialid() FOR traId
go

ALTER TABLE Vehicule
    ADD CONSTRAINT DF_vehId DEFAULT newsequentialid() FOR vehId
go

/* FIN MODIFICATION  */
